
services:
  # BE Database
  postgres_be:
    image: pgvector/pgvector:pg16 
    container_name: postgres_be
    restart: always
    environment:
      POSTGRES_DB: be_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: portgasDace
    ports:
      -  "5543:5432"    
    volumes:
      - be_data:/var/lib/postgresql/data
    networks:
      - datn_net

  # AI Database
  postgres_ai:
    image: pgvector/pgvector:pg16
    container_name: postgres_ai
    restart: always
    environment:
      POSTGRES_DB: ai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: portgasDace
    ports:
      - "5544:5432"   # AI Postgres exposed on 5434
    volumes:
      - ai_data:/var/lib/postgresql/data
    networks:
      - datn_net

  # PGAdmin (optional)
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-viet.info.43@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-portgasDace}
    ports:
      - "5050:80"
    networks:
      - datn_net
    depends_on:
      - postgres_be
      - postgres_ai

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports: ["11435:11434"]
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*  
    volumes:
      - ollama:/root/.ollama

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - datn_net

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data 
    networks:
      - datn_net
volumes:
  ollama:
  openwebui:
  be_data:
  ai_data:
  minio-data:
  redis_data:

networks:
  datn_net:

